import { Request, Response } from 'express';
import prisma from '../config/database';

// POST /api/posts
// Creates a new post for the authenticated Level 3 user.
// All four post types are supported: GENERAL_TIP, SEAT_TIP, PUB_RECOMMENDATION, IM_GOING.
// The authorName and authorEmail are fetched from the database (not trusted from the request body)
// to ensure the displayed name is always accurate and cannot be spoofed.
// Returns 201 with the created post object.
export const createPost = async (req: Request, res: Response) => {
  try {
    // The allowed post types — we validate against this list rather than importing the Prisma enum
    // at runtime, which keeps the validation simple and readable
    const VALID_POST_TYPES = ['GENERAL_TIP', 'SEAT_TIP', 'PUB_RECOMMENDATION', 'IM_GOING', 'GETTING_THERE'];

    const {
      postType,
      teamId,
      title,
      body,
      seatSection,
      seatRow,
      seatNumber,
      seatRating,
      pubName,
      pubAddress,
      pubDistance,
      matchId,
      transportType,
      travelCost,
      travelTime,
      photoUrl,
    } = req.body;

    // Validate required fields
    if (!postType || !VALID_POST_TYPES.includes(postType)) {
      return res.status(400).json({
        error: 'postType is required and must be one of: GENERAL_TIP, SEAT_TIP, PUB_RECOMMENDATION, IM_GOING, GETTING_THERE',
      });
    }

    if (!teamId) {
      return res.status(400).json({ error: 'teamId is required' });
    }

    if (!title || !body) {
      return res.status(400).json({ error: 'title and body are required' });
    }

    // Fetch the user from the database to get their real name and email.
    // We do NOT use the authorName from req.body — it can't be trusted.
    // req.auth is guaranteed to exist here because requireLevel3 ran before this controller.
    const user = await prisma.user.findUnique({ where: { id: req.auth!.userId } });
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Create the post. Optional type-specific fields are only included if they were provided
    // in the request body — we use conditional spread to avoid overwriting DB defaults with undefined.
    const post = await prisma.post.create({
      data: {
        teamId,
        postType,
        title,
        body,
        authorName: user.name,
        authorEmail: user.email,
        userId: user.id,
        ...(seatSection !== undefined && { seatSection }),
        ...(seatRow !== undefined && { seatRow }),
        ...(seatNumber !== undefined && { seatNumber }),
        ...(seatRating !== undefined && { seatRating: Number(seatRating) }),
        ...(pubName !== undefined && { pubName }),
        ...(pubAddress !== undefined && { pubAddress }),
        ...(pubDistance !== undefined && { pubDistance }),
        ...(matchId !== undefined && { matchId: Number(matchId) }),
        // GETTING_THERE transport fields — only set when the post type is GETTING_THERE
        ...(transportType !== undefined && { transportType }),
        ...(travelCost !== undefined && { travelCost }),
        ...(travelTime !== undefined && { travelTime }),
        // photoUrl is an optional Azure Blob URL set when the user attaches a photo
        photoUrl: photoUrl || null,
      },
    });

    return res.status(201).json(post);
  } catch (error) {
    console.error('Error creating post:', error);
    res.status(500).json({ error: 'Failed to create post' });
  }
};

// POST /api/posts/:postId/upvote
// Toggles an upvote on a post for the authenticated user (Level 3 required).
// Uses a Prisma transaction to keep the upvote row and upvoteCount counter in sync atomically.
// Returns { upvoted: boolean, upvoteCount: number }
export const toggleUpvote = async (req: Request, res: Response) => {
  try {
    const postId = parseInt(req.params.postId, 10);
    if (isNaN(postId)) {
      return res.status(400).json({ error: 'postId must be a number' });
    }

    // req.auth is guaranteed to exist here because requireLevel3 ran first
    const userId = req.auth!.userId;

    // Check if this user has already upvoted the post
    // The compound key name `postId_userId` is auto-generated by Prisma from @@unique([postId, userId])
    const existingUpvote = await prisma.upvote.findUnique({
      where: { postId_userId: { postId, userId } },
    });

    let updatedPost;

    if (existingUpvote) {
      // User already upvoted — toggle OFF: delete the upvote row and decrement the counter
      // We use a transaction so both operations succeed or both fail together
      await prisma.$transaction([
        prisma.upvote.delete({ where: { postId_userId: { postId, userId } } }),
        prisma.post.update({
          where: { id: postId },
          data: { upvoteCount: { decrement: 1 } },
        }),
      ]);

      // Fetch the updated post to get the real upvoteCount after the transaction
      updatedPost = await prisma.post.findUnique({ where: { id: postId } });

      return res.json({ upvoted: false, upvoteCount: updatedPost?.upvoteCount ?? 0 });
    } else {
      // User has not upvoted yet — toggle ON: create the upvote row and increment the counter
      await prisma.$transaction([
        prisma.upvote.create({ data: { postId, userId } }),
        prisma.post.update({
          where: { id: postId },
          data: { upvoteCount: { increment: 1 } },
        }),
      ]);

      // Fetch the updated post to get the real upvoteCount after the transaction
      updatedPost = await prisma.post.findUnique({ where: { id: postId } });

      return res.json({ upvoted: true, upvoteCount: updatedPost?.upvoteCount ?? 0 });
    }
  } catch (error) {
    console.error('Error toggling upvote:', error);
    res.status(500).json({ error: 'Failed to toggle upvote' });
  }
};

// PUT /api/posts/:postId
// Lets the authenticated author edit their own post.
// Only the post's original author can edit — returns 403 if someone else tries.
// Only updates fields that are present in the request body (sparse update).
// Returns 200 with the updated post object.
export const editPost = async (req: Request, res: Response) => {
  try {
    const postId = parseInt(req.params.postId, 10);
    if (isNaN(postId)) {
      return res.status(400).json({ error: 'postId must be a number' });
    }

    // Find the post to verify it exists and to check ownership
    const post = await prisma.post.findUnique({ where: { id: postId } });
    if (!post) {
      return res.status(404).json({ error: 'Post not found' });
    }

    // Only the post's author may edit it
    // post.userId can be null (email-only Level 2 posts), which will always fail the check
    if (post.userId !== req.auth!.userId) {
      return res.status(403).json({ error: 'You can only edit your own posts' });
    }

    const body = req.body;

    // Only update fields that are explicitly present in the request body.
    // Spreading undefined values into the data object would overwrite existing data with undefined,
    // so we use conditional spread for each optional field.
    const updatedPost = await prisma.post.update({
      where: { id: postId },
      data: {
        ...(body.title !== undefined && { title: body.title }),
        ...(body.body !== undefined && { body: body.body }),
        ...(body.seatSection !== undefined && { seatSection: body.seatSection }),
        ...(body.seatRow !== undefined && { seatRow: body.seatRow }),
        ...(body.seatNumber !== undefined && { seatNumber: body.seatNumber }),
        ...(body.seatRating !== undefined && { seatRating: body.seatRating }),
        ...(body.pubName !== undefined && { pubName: body.pubName }),
        ...(body.pubAddress !== undefined && { pubAddress: body.pubAddress }),
        ...(body.pubDistance !== undefined && { pubDistance: body.pubDistance }),
        // GETTING_THERE transport fields — only updated when present in the request body
        ...(body.transportType !== undefined && { transportType: body.transportType }),
        ...(body.travelCost !== undefined && { travelCost: body.travelCost }),
        ...(body.travelTime !== undefined && { travelTime: body.travelTime }),
      },
    });

    res.json(updatedPost);
  } catch (error) {
    console.error('Error editing post:', error);
    res.status(500).json({ error: 'Failed to edit post' });
  }
};

// DELETE /api/posts/:postId
// Lets the authenticated author delete their own post.
// Only the post's original author can delete — returns 403 if someone else tries.
// Deletes related upvotes first to avoid a foreign key constraint error,
// then deletes the post itself.
// Returns 200 with { message: 'Post deleted' }
export const deletePost = async (req: Request, res: Response) => {
  try {
    const postId = parseInt(req.params.postId, 10);
    if (isNaN(postId)) {
      return res.status(400).json({ error: 'postId must be a number' });
    }

    // Find the post to verify it exists and to check ownership
    const post = await prisma.post.findUnique({ where: { id: postId } });
    if (!post) {
      return res.status(404).json({ error: 'Post not found' });
    }

    // Only the post's author may delete it
    if (post.userId !== req.auth!.userId) {
      return res.status(403).json({ error: 'You can only delete your own posts' });
    }

    // Delete upvotes first — the Upvote table has a foreign key to Post.
    // Trying to delete the Post first would throw a constraint violation.
    await prisma.upvote.deleteMany({ where: { postId } });

    // Now it's safe to delete the post itself
    await prisma.post.delete({ where: { id: postId } });

    res.json({ message: 'Post deleted' });
  } catch (error) {
    console.error('Error deleting post:', error);
    res.status(500).json({ error: 'Failed to delete post' });
  }
};
