import { Request, Response } from 'express';
import prisma from '../config/database';

// POST /api/users/favorites/:teamId
// Toggles a team as a favorite for the authenticated user (Level 3 required).
// Returns { favorited: true } when added, { favorited: false } when removed.
export const toggleFavorite = async (req: Request, res: Response) => {
  try {
    const teamId = parseInt(req.params.teamId, 10);
    if (isNaN(teamId)) {
      return res.status(400).json({ error: 'teamId must be a number' });
    }

    // req.auth is guaranteed to exist here because requireLevel3 ran first
    const userId = req.auth!.userId;

    // Check if this user has already favorited this team
    // The compound key name `userId_teamId` is auto-generated by Prisma from @@unique([userId, teamId])
    const existingFavorite = await prisma.userFavorite.findUnique({
      where: { userId_teamId: { userId, teamId } },
    });

    if (existingFavorite) {
      // Already favorited — remove it (toggle off)
      await prisma.userFavorite.delete({
        where: { userId_teamId: { userId, teamId } },
      });
      return res.json({ favorited: false });
    } else {
      // Not favorited yet — add it (toggle on)
      await prisma.userFavorite.create({
        data: { userId, teamId },
      });
      return res.json({ favorited: true });
    }
  } catch (error) {
    console.error('Error toggling favorite:', error);
    res.status(500).json({ error: 'Failed to toggle favorite' });
  }
};

// GET /api/users/favorites
// Returns the list of team IDs the authenticated user has favorited.
// The frontend uses this on page load to set the initial state of heart icons.
export const getFavorites = async (req: Request, res: Response) => {
  try {
    const userId = req.auth!.userId;

    // Fetch only the teamId field — we just need the IDs to compare against displayed teams
    const favorites = await prisma.userFavorite.findMany({
      where: { userId },
      select: { teamId: true },
    });

    res.json({ favoriteTeamIds: favorites.map(f => f.teamId) });
  } catch (error) {
    console.error('Error fetching favorites:', error);
    res.status(500).json({ error: 'Failed to fetch favorites' });
  }
};
